name:                fp2025
version:             0.1.0.0
github:              "vipo/fp-2025"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/fp2024#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- bytestring
- http-types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - deepseq
    - free
    - QuickCheck
    - random
    - stm
    - strict
    - transformers
    - async
    - bytestring
    - http-conduit
    - http-client
    - http-types

executables:
  fp2025-client:
    main: Main.hs
    source-dirs: app-client
    ghc-options:
      - -rtsopts
    dependencies:
      - fp2025
      - http-conduit
      - http-client
      - http-types
      - bytestring
      - text
      - stm
      - transformers

  fp2025-server:
    main: Main.hs
    source-dirs: app-server
    ghc-options:
      - -rtsopts
    dependencies:
      - fp2025
      - scotty
      - wai
      - wai-extra
      - http-types
      - text
      - bytestring
      - stm
      - transformers

tests:
  fp2025-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fp2025
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - transformers
      - free
      - scotty
      - http-client
      - http-types
      - http-conduit
      - wai
      - wai-extra
      - text
      - bytestring
      - QuickCheck
      - mtl